spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/certRecognition
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    database: 1
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 200Mb

server:
  port: 8089

logging:
  file: logs/CertificationRecognition_backend.log
  level:
    org:
      springframework:
        security: DEBUG
        web: ERROR
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread] %cyan(%logger{15}) - %highlight(%msg) %n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread] %cyan(%logger{15}) - %highlight(%msg) %n'

head:
  path: F:/CertificationRecognition_backend/head/

photo:
  path: F:/CertificationRecognition_backend/photo/

python:
  path: D:/360Downloads/pythonWorkplace/CertificationRecognition_recognition/Application.py
